version: '2'

services:

 shop:
   image: shop:latest
   container_name: internetShop
   hostname: shop
   ports:
   - 8081:8080
   depends_on:
   - rabbit

 app:
  image: showcase:latest
  container_name: internetShowcase
  ports:
     - 8085:8080
  depends_on:
    - shop
    - rabbit

 rabbit:
  image: rabbitmq:3-management
  hostname: my-rabbit
  container_name: my-rabbit
  environment:
     RABBITMQ_DEFAULT_USER: 'admin'
     RABBITMQ_DEFAULT_PASS: 'admin'
  ports:
    - 8080:15672
    - 5672:5672